/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BandId = IDL.Nat;
export const Band = IDL.Record({
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'foundingYear' : IDL.Nat,
  'genres' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBand' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
      [BandId],
      [],
    ),
  'getAllBands' : IDL.Func([], [IDL.Vec(Band)], ['query']),
  'getBand' : IDL.Func([BandId], [IDL.Opt(Band)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BandId = IDL.Nat;
  const Band = IDL.Record({
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'foundingYear' : IDL.Nat,
    'genres' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addBand' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Nat],
        [BandId],
        [],
      ),
    'getAllBands' : IDL.Func([], [IDL.Vec(Band)], ['query']),
    'getBand' : IDL.Func([BandId], [IDL.Opt(Band)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };